In [1]:
import pandas as pd

In [8]:
import redis as rd

In [5]:
D=pd.read_excel("https://github.com/junaart/ForStudents/raw/refs/heads/main/R/Zachet/DataSets/5.xlsx")
D

,town1,Sum-Avg-Р811,Sum-Avg-Р812,Sum-Avg-Р813,Sum-Avg-Р814,Sum-Avg-Р815,Sum-Avg-Р821,Sum-Avg-Р822,Sum-Avg-Р823,Sum-Avg-Р824,Sum-Avg-Р825,Sum-Avg-Р826
0,Абакан,1.918825e+03,8954.6250,33.725000,1796.25000,11138.525000,2.541233e+04,130.3000,30.0000,18.850000,17.200000,0.000000
1,Азовский район,6.811933e+03,0.0000,0.000000,0.00000,79440.066667,9.480033e+03,0.0000,815.1000,0.000000,48562.933333,0.000000
2,Аксайский район,7.125582e+04,0.0000,0.000000,0.00000,51530.400000,8.716662e+04,0.0000,4957.3925,0.000000,41171.825000,6267.700000
3,Алексеевкий район,1.230500e+03,0.0000,0.000000,0.00000,371.900000,4.782000e+02,0.0000,0.0000,0.000000,0.000000,0.000000
4,Анапа,8.225300e+03,0.0000,0.000000,0.00000,4965.700000,2.213350e+03,0.0000,0.0000,0.000000,0.000000,2752.350000
...,...,...,...,...,...,...,...,...,...,...,...,...
276,Южно-Сахалинск,4.128817e+05,6014.1500,133902.700000,94626.55000,148720.115000,8.441777e+05,956.9055,87.9500,315633.283250,948.500000,2593.877500
277,Якутск,1.711287e+06,136877.2175,88569.590500,11221.81025,114265.795250,2.173559e+06,17260.6250,4784.8375,5677.307500,3841.350000,158407.882500
278,Ялта,3.921625e+05,111159.7000,925.000000,100.00000,21083.150000,5.135638e+05,4912.2500,0.0000,1.650000,50144.500000,3393.100000
279,Ярославль,2.688059e+05,204442.7000,92436.108333,4781.80000,138296.366667,4.082314e+05,3007.3750,203.7500,594857.658333,1571.075000,34727.841667
280,Ярославский район,1.544818e+04,0.0000,0.000000,0.00000,7137.453333,2.118627e+04,0.0000,10.0000,0.000000,593.373333,753.663333

In [23]:
r=rd.Redis(host='localhost', db=0)
key = "col"
for i in range(len(D['Sum-Avg-Р811'])):
    r.set(key+str(i),str(D['Sum-Avg-Р811'].iloc[i]))

In [10]:
r=rd.Redis(host='localhost', db=0)
key = "col2"
for i in range(len(D['Sum-Avg-Р812'])):
    r.set(key+str(i),str(D['Sum-Avg-Р812'].iloc[i]))

In [11]:
r=rd.Redis(host='localhost', db=0)
key = "col3"
for i in range(len(D['Sum-Avg-Р813'])):
    r.set(key+str(i),str(D['Sum-Avg-Р813'].iloc[i]))

In [12]:
r=rd.Redis(host='localhost', db=0)
key = "col4"
for i in range(len(D['Sum-Avg-Р814'])):
    r.set(key+str(i),str(D['Sum-Avg-Р814'].iloc[i]))

In [15]:
r=rd.Redis(host='localhost', db=0)
key = "col5"
for i in range(len(D['Sum-Avg-Р815'])):
    r.set(key+str(i),str(D['Sum-Avg-Р815'].iloc[i]))

In [16]:
r=rd.Redis(host='localhost', db=0)
key = "col6"
for i in range(len(D['Sum-Avg-Р821'])):
    r.set(key+str(i),str(D['Sum-Avg-Р821'].iloc[i]))

In [17]:
r=rd.Redis(host='localhost', db=0)
key = "col7"
for i in range(len(D['Sum-Avg-Р821'])):
    r.set(key+str(i),str(D['Sum-Avg-Р821'].iloc[i]))

In [18]:
r=rd.Redis(host='localhost', db=0)
key = "col8"
for i in range(len(D['Sum-Avg-Р822'])):
    r.set(key+str(i),str(D['Sum-Avg-Р822'].iloc[i]))

In [19]:
r=rd.Redis(host='localhost', db=0)
key = "col9"
for i in range(len(D['Sum-Avg-Р823'])):
    r.set(key+str(i),str(D['Sum-Avg-Р823'].iloc[i]))

In [20]:
r=rd.Redis(host='localhost', db=0)
key = "col10"
for i in range(len(D['Sum-Avg-Р824'])):
    r.set(key+str(i),str(D['Sum-Avg-Р824'].iloc[i]))

In [21]:
r=rd.Redis(host='localhost', db=0)
key = "col11"
for i in range(len(D['Sum-Avg-Р825'])):
    r.set(key+str(i),str(D['Sum-Avg-Р825'].iloc[i]))

In [22]:
r=rd.Redis(host='localhost', db=0)
key = "col12"
for i in range(len(D['Sum-Avg-Р826'])):
    r.set(key+str(i),str(D['Sum-Avg-Р826'].iloc[i]))